Repository TerriaJS/terriajs, pull requests merged in 2019-10, with the labels that each got.

#3679 Support coords crossing anti-meridian in 2D mode with geojson
  CHANGES.md
  lib/Map/LeafletVisualizer.js
Labels: P-PacificMap

#3726 Mobx charts - victory charts + colors + chart item selector
  lib/Charts/ChartData.ts
  lib/Charts/ChartRenderer.ts
  lib/Charts/ChartView.ts
  lib/Charts/getChartColorForId.ts
  lib/ModelMixins/AsyncChartableMixin.ts
  lib/ModelMixins/TableMixin.ts
  lib/Models/Chartable.ts
  lib/ReactViews/Custom/Chart/BottomDockChart.jsx
  lib/ReactViews/Custom/Chart/Chart.jsx
  lib/ReactViews/Custom/Chart/ChartPanel.jsx
  lib/ReactViews/Custom/Chart/FeatureInfoPanelChart.jsx
  lib/ReactViews/Custom/Chart/NewChart.jsx
  lib/ReactViews/Custom/ChartCustomComponent.ts
  lib/ReactViews/Custom/parseCustomMarkdownToReact.js
  lib/ReactViews/Workbench/Controls/ChartItemSelector.jsx
  lib/ReactViews/Workbench/Controls/chart-item-selector.scss
  lib/ReactViews/Workbench/Controls/chart-item-selector.scss.d.ts
  lib/ReactViews/Workbench/WorkbenchItem.jsx
  lib/Traits/TableChartStyleTraits.ts
  lib/Traits/objectArrayTrait.ts
  lib/Traits/objectTrait.ts
  package.json
Labels: High priority, P - DigitalTwin

#3742 Very rough approach for implementing language settings
  CHANGES.md
  lib/Language/defaults.jsx
  lib/Models/Terria.js
  lib/ReactViews/Custom/registerCustomComponentTypes.js
  lib/ReactViews/Feedback/FeedbackButton.jsx
  lib/ReactViews/SidePanel/EmptyWorkbenchMessage.jsx
  lib/ReactViews/SidePanel/SidePanel.jsx
  lib/ReactViews/StandardUserInterface/MapColumn.jsx
Labels: High priority, P-SatelliteImagery

#3740 Pass a custom update interval to leaflet tile layers
  CHANGES.md
  lib/Map/CesiumTileLayer.js
  lib/Models/ImageryLayerCatalogItem.js
Labels: High priority, P-SatelliteImagery

#3743 3708 workbench guidance
  CHANGES.md
  lib/Language/defaults.jsx
  lib/Models/Terria.js
  lib/Models/WebMapServiceCatalogItem.js
  lib/ReactViewModels/ViewState.js
  lib/ReactViews/DataCatalog/DataCatalogItem.jsx
  lib/ReactViews/Guidance/Guidance.jsx
  lib/ReactViews/Guidance/GuidanceDot.jsx
  lib/ReactViews/Guidance/guidance-dot.scss
  lib/ReactViews/Guidance/guidance.scss
  lib/ReactViews/Guide/Guide.jsx
  lib/ReactViews/Guide/SatelliteGuide.jsx
  lib/ReactViews/Guide/guide.scss
  lib/ReactViews/Guide/satellite-guidance.js
  lib/ReactViews/HelpScreens/HelpMenuPanelBasic.jsx
  lib/ReactViews/HelpScreens/help-panel.scss
  lib/ReactViews/Hooks/useKeyPress.js
  lib/ReactViews/Map/MenuBar.jsx
  lib/ReactViews/Map/menu-bar.scss
  lib/ReactViews/Mobile/MobileMenu.jsx
  lib/ReactViews/Preview/MappablePreview.jsx
  lib/ReactViews/ReactHelpers/getReactElementFromContents.js
  lib/ReactViews/SidePanel/EmptyWorkbenchMessage.jsx
  lib/ReactViews/SidePanel/SidePanel.jsx
  lib/ReactViews/StandardUserInterface/MapColumn.jsx
  lib/ReactViews/StandardUserInterface/StandardUserInterface.jsx
  lib/ReactViews/Transitions/FadeIn/FadeIn.jsx
  lib/ReactViews/Transitions/FadeIn/fade-in.scss
  lib/ReactViews/Transitions/SlideUpFadeIn/SlideUpFadeIn.jsx
  lib/ReactViews/Transitions/SlideUpFadeIn/slide-up-fade-in.scss
  lib/ReactViews/WelcomeMessage/WelcomeMessage.jsx
  lib/ReactViews/WelcomeMessage/welcome-message.scss
  lib/Styled/Spacing.jsx
  lib/Styled/Text.jsx
  lib/Styled/text.scss
  package.json
  test/Models/TerriaSpec.js
  wwwroot/images/guides/satellite-feature.jpg
  wwwroot/images/guides/satellite-location.jpg
  wwwroot/images/guides/satellite-styles.jpg
  wwwroot/images/guides/satellite-time.jpg
  wwwroot/images/guides/satellite-zoom.jpg
Labels: High priority, P-SatelliteImagery
