Repository TerriaJS/terriajs, pull requests merged in 2019-09, with the labels that each got.

#3627 Embedded data links
  lib/ReactViews/Preview/Description.js
Labels: P-AREMI

#3678 Mobx terrace
  lib/ModelMixins/GroupMixin.ts
  lib/Models/MagdaCatalogGroup.ts
  lib/Models/Terria.ts
  lib/Models/magdaRecordToCatalogMember.ts
  test/Models/upsertModelFromJsonSpec.ts
Labels: New Model Architecture

#3686 Add chrome workaround until browser bug is resolved
  lib/ReactViews/StandardUserInterface/MapColumn.jsx
  lib/ReactViews/StandardUserInterface/map-column.scss
Labels: T-Bug

#3689 Add chrome workaround until browser bug is resolved
  lib/ReactViews/StandardUserInterface/MapColumn.jsx
  lib/ReactViews/StandardUserInterface/map-column.scss
  lib/ReactViews/StandardUserInterface/map-column.scss.d.ts
Labels: T-Bug

#3622 Model architecture: Charts
  lib/Charts/BarChart.js
  lib/Charts/BaseChart.js
  lib/Charts/ChartData.js
  lib/Charts/ChartData.ts
  lib/Charts/ChartRenderer.js
  lib/Charts/ChartRenderer.ts
  lib/Charts/Scales.js
  lib/Charts/Size.js
  lib/Charts/Title.js
  lib/Charts/Tooltip.js
  lib/Charts/initializeChartTypes.js
  lib/ModelMixins/AsyncChartableMixin.ts
  lib/ModelMixins/AsyncMappableMixin.ts
  lib/ModelMixins/TableMixin.ts
  lib/Models/Cesium3DTilesCatalogItem.ts
  lib/Models/Chartable.ts
  lib/Models/CsvCatalogItem.ts
  lib/Models/CzmlCatalogItem.ts
  lib/Models/GeoJsonCatalogItem.ts
  lib/Models/GtfsCatalogItem.ts
  lib/ReactViewModels/SearchState.ts
  lib/ReactViews/BottomDock/BottomDock.jsx
  lib/ReactViews/Custom/Chart/Chart.jsx
  lib/ReactViews/Custom/Chart/ChartExpandAndDownloadButtons.jsx
  lib/ReactViews/Custom/Chart/ChartPanel.jsx
  lib/ReactViews/Custom/Chart/NewChart.jsx
  lib/ReactViews/Custom/Chart/chart-panel-download-button.scss.d.ts
  lib/ReactViews/Custom/Chart/chart-panel.scss.d.ts
  lib/ReactViews/Custom/ChartCustomComponent.ts
  lib/ReactViews/Custom/Collapsible/Collapsible.jsx
  lib/ReactViews/Custom/CollapsibleCustomComponent.ts
  lib/ReactViews/Custom/CustomComponent.ts
  lib/ReactViews/Custom/CustomComponentType.js
  lib/ReactViews/Custom/CustomComponents.js
  lib/ReactViews/Custom/parseCustomHtmlToReact.js
  lib/ReactViews/Custom/parseCustomMarkdownToReact.js
  lib/ReactViews/Custom/registerCustomComponentTypes.js
  lib/ReactViews/FeatureInfo/FeatureInfoSection.jsx
  lib/Table/TableAutomaticStylesStratum.ts
  lib/Table/TableColumn.ts
  lib/Table/TableStyle.ts
  lib/Traits/TableChartStyleTraits.ts
  package.json
Labels: P - DigitalTwin
