Repository TerriaJS/terriajs, pull requests merged in 2020-04, with the labels that each got.

#4140 fixed Cesium3DTilesCatalogItem to work with ionAssetIds
  lib/Models/Cesium3DTilesCatalogItem.ts
Labels: T-Bug, mobX

#4139 Mobx dragdrop file fix
  CHANGES.md
  lib/Core/loadBlob.ts
  lib/Models/CsvCatalogItem.ts
  lib/Models/GtfsCatalogItem.ts
  lib/Models/UrlReference.ts
  lib/Models/addUserFiles.ts
  lib/Models/createCatalogItemFromFileOrUrl.ts
  lib/Models/createUrlReferenceFromUrl.ts
  lib/Models/registerCatalogMembers.ts
  lib/ReactViewModels/ViewState.ts
  lib/ReactViews/DragDropFile.jsx
  lib/ReactViews/DragDropNotification.jsx
  lib/ReactViews/StandardUserInterface/StandardUserInterface.jsx
  lib/ReactViews/drag-drop-file.scss.d.ts
  lib/ReactViews/drag-drop-notification.scss.d.ts
  test/Models/TerriaSpec.ts
  test/Models/createCatalogItemFromUrlSpec.ts
Labels: P-YourDataYourRegions, T-Bug, mobX

#4213 Mobx tighten gyro
  CHANGES.md
  doc/contributing/styled-components-and-sass.md
  lib/ReactViews/CleanDropdownPanel/CleanDropdownPanel.jsx
  lib/ReactViews/GyroscopeGuidance/GyroscopeGuidance.jsx
  lib/ReactViews/Icon.jsx
  lib/ReactViews/Map/Navigation/Compass.jsx
  lib/ReactViews/Map/Navigation/MyLocation.jsx
  lib/ReactViews/Map/Navigation/compass.scss
  lib/ReactViews/Map/Navigation/compass.scss.d.ts
  lib/ReactViews/Map/Panels/HelpPanel/HelpPanel.jsx
  lib/ReactViews/Map/Panels/InnerPanel.jsx
  lib/ReactViews/MapIconButton/MapIconButton.jsx
  lib/ReactViews/StandardUserInterface/StandardTheme.jsx
  lib/Sass/common/_variables-export.scss
  lib/Styled/Box.jsx
  lib/Styled/Spacing.jsx
  lib/Styled/Text.jsx
  lib/Styled/mixins.js
  test/ReactViews/GyroscopeGuidance/GyroscopeGuidanceSpec.tsx
  test/ReactViews/Map/Navigation/Compass/CompassSpec.tsx
  wwwroot/images/icons/compass-outer-enlarged.svg
  wwwroot/images/icons/compass-outer-skeleton.svg
  wwwroot/images/icons/help-thick.svg
Labels: mobX

#4248 Fixes FeatureInfoPanel port from #4240 & some wrong proptypes
  CHANGES.md
  lib/ReactViews/Feedback/FeedbackButton.jsx
  lib/ReactViews/MapIconButton/MapIconButton.jsx
Labels: mobX
