Repository TerriaJS/terriajs, pull requests merged in 2020-07, with the labels that each got.

#4508 Next: Add header option to loadText
  CHANGES.md
  lib/Core/loadText.js
Labels: P-YourDataYourRegions, Z-Small

#4507 Next: Add typeName to CatalogMemberMixin
  CHANGES.md
  lib/ModelMixins/CatalogMemberMixin.ts
  lib/Models/WebProcessingServiceCatalogFunction.ts
Labels: P-YourDataYourRegions, Z-Small

#4512 Add refreshEnabled trait and AsyncMappableMixin to AutoRefreshMixin
  CHANGES.md
  lib/ModelMixins/AutoRefreshingMixin.ts
  lib/Models/CsvCatalogItem.ts
  lib/Traits/AutoRefreshingTraits.ts
  lib/Traits/CsvCatalogItemTraits.ts
  test/ModelMixins/TableMixinSpec.ts
Labels: P-YourDataYourRegions

#4516 Add show to ShortReportTraits and Tsxify ShortReport
  CHANGES.md
  lib/Models/ShortReportSection.js
  lib/ReactViews/Icon.jsx
  lib/ReactViews/Workbench/Controls/ShortReport.jsx
  lib/ReactViews/Workbench/Controls/ShortReport.tsx
  lib/ReactViews/Workbench/Controls/short-report.scss
  lib/ReactViews/Workbench/Controls/short-report.scss.d.ts
  lib/Traits/CatalogMemberTraits.ts
  test/ReactViews/ShortReportSpec.tsx
Labels: P-YourDataYourRegions, Version 8

#4429 Mobx search breadcrumb
  CHANGES.md
  lib/Core/getPath.ts
  lib/Models/getAncestors.ts
  lib/ReactViewModels/ViewState.ts
  lib/ReactViews/DataCatalog/DataCatalogGroup.jsx
  lib/ReactViews/DataCatalog/DataCatalogItem.jsx
  lib/ReactViews/ExplorerWindow/Tabs/DataCatalogTab.jsx
  lib/ReactViews/Icon.jsx
  lib/ReactViews/Preview/data-preview.scss
  lib/ReactViews/Search/Breadcrumbs.jsx
  test/ReactViews/Search/BreadcrumbsSpec.tsx
  wwwroot/images/icons/globe.svg
Labels: Low priority

#4496 Mobx: ArcGisPortal models
  lib/Language/en/translation.json
  lib/Models/ArcGisPortalCatalogGroup.ts
  lib/Models/ArcGisPortalDefinitions.ts
  lib/Models/ArcGisPortalItemReference.ts
  lib/Models/registerCatalogMembers.ts
  lib/Traits/ArcGisPortalCatalogGroupTraits.ts
  lib/Traits/ArcGisPortalItemFormatTraits.ts
  lib/Traits/ArcGisPortalItemTraits.ts
  lib/Traits/ArcGisPortalSharedTraits.ts
  package.json
  test/Models/ArcGisPortalCatatalogGroupSpec.ts
  test/Models/ArcGisPortalReferenceItemSpec.ts
  wwwroot/test/ArcGisPortal/group-2dfa6cfea7774d9585700059e1fc8219-items-search.json
  wwwroot/test/ArcGisPortal/group-c86af18fa4a74336b1feee2a0ee4883d-items-search.json
  wwwroot/test/ArcGisPortal/group-search-results.json
  wwwroot/test/ArcGisPortal/item-data.json
  wwwroot/test/ArcGisPortal/item.json
  wwwroot/test/ArcGisPortal/search-result.json
  wwwroot/test/ArcGisPortal/user-info.json
Labels: High priority, P - DigitalTwin
