Repository TerriaJS/terriajs, pull requests merged in 2020-08, with the labels that each got.

#4393 Mobx Legend improvements for TableMixin
  CHANGES.md
  lib/ModelMixins/TableMixin.ts
  lib/ReactViews/Workbench/Controls/Legend.jsx
  lib/Table/TableAutomaticStylesStratum.ts
  lib/Traits/LegendTraits.ts
  lib/Traits/TableTraits.ts
Labels: C-Legends, Needs Discussion, P-YourDataYourRegions, T-Enhancement, Version 8

#4642 Make Drag & Drop great again
  lib/ModelMixins/TimeVarying.ts
  lib/Models/ResultPendingCatalogItem.ts
  lib/Models/addUserCatalogMember.ts
  lib/Models/addUserFiles.ts
  lib/ReactViews/DragDropFile.jsx
  lib/ReactViews/DragDropFile.tsx
Labels: C-User-added data, T-Bug, Version 8

#4386 Update to use Cesium's new typescript definitions
  CHANGES.md
  architecture/0002-require-instead-of-import.md
  lib/Core/CorsProxy.ts
  lib/Map/CesiumSelectionIndicator.ts
  lib/Map/CesiumTileLayer.ts
  lib/Map/LeafletVisualizer.ts
  lib/Map/MapboxVectorTileImageryProvider.ts
  lib/ModelMixins/DiffableMixin.ts
  lib/ModelMixins/FeatureInfoMixin.ts
  lib/ModelMixins/TimeFilterMixin.ts
  lib/ModelMixins/TimeVarying.ts
  lib/Models/ArcGisFeatureServerCatalogItem.ts
  lib/Models/BingMapsSearchProvider.ts
  lib/Models/CartoMapCatalogItem.ts
  lib/Models/Cesium.ts
  lib/Models/GeoJsonCatalogItem.ts
  lib/Models/GlobeOrMap.ts
  lib/Models/GltfCatalogItem.ts
  lib/Models/GtfsCatalogItem.ts
  lib/Models/KmlCatalogItem.ts
  lib/Models/Leaflet.ts
  lib/Models/Mappable.ts
  lib/Models/NoViewer.ts
  lib/Models/TimelineStack.ts
  lib/Models/UserDrawing.ts
  lib/Models/WebMapServiceCatalogItem.ts
  lib/Models/callWebCoverageService.ts
  lib/Table/createLongitudeLatitudeFeaturePerId.ts
  lib/Table/createLongitudeLatitudeFeaturePerRow.ts
  lib/ThirdParty/terriajs-cesium-extra/index.d.ts
  lib/ThirdParty/terriajs-cesium/index.d.ts
  package.json
  test/ModelMixins/TableMixinSpec.ts
  test/Models/ArcGisFeatureServerCatalogItemSpec.ts
  test/Models/GltfCatalogItemSpec.ts
  test/Models/UserDrawingSpec.ts
  tsconfig-node.json
  tsconfig.json
Labels: High priority, Version 8
