Repository TerriaJS/terriajs, pull requests merged in 2020-11, with the labels that each got.

#4923 WMS legend improvements for default styles
  CHANGES.md
  lib/Language/en/translation.json
  lib/Models/SelectableDimensions.ts
  lib/Models/WebMapServiceCatalogItem.ts
  lib/ReactViews/Workbench/Controls/DimensionSelectorSection.tsx
  test/Models/WebMapServiceCatalogItemSpec.ts
  test/ReactViews/DimensionSelectorSectionSpec.tsx
Labels: C-Legends, T-Bug, Version 8

#4962 Add catalog function ADR
  architecture/0004-next-catalog-functions.md
Labels: T-Documentation

#4326 Mobx: Ensure there aren't more bins than unique values
  CHANGES.md
  lib/Table/TableStyle.ts
  lib/Table/colorbrewer.json
  test/Table/TableStyleSpec.ts
Labels: Low priority

#4520 Improve handling for ArcGisMapServerCatalogItem
  CHANGES.md
  lib/Language/en/translation.json
  lib/Models/ArcGisMapServerCatalogItem.ts
Labels: Medium priority

#4979 Improve magda root group behaviour for sharing
  CHANGES.md
  lib/Models/Terria.ts
  test/Models/TerriaSpec.ts
Labels: Version 8

#4957 Fix missing padlock
  CHANGES.md
  lib/Models/ArcGisPortalCatalogGroup.ts
  lib/Models/ArcGisPortalItemReference.ts
Labels: Medium priority

#4919 Workbench loading issues
  CHANGES.md
  lib/ModelMixins/CatalogFunctionJobMixin.ts
  lib/ModelMixins/CatalogFunctionMixin.ts
  lib/Models/Terria.ts
  lib/Models/Workbench.ts
  lib/Models/addToWorkbench.ts
  lib/Models/addUserCatalogMember.ts
  lib/ReactViews/Custom/Chart/ChartExpandAndDownloadButtons.tsx
  lib/ReactViews/DataCatalog/DataCatalogItem.jsx
  lib/ReactViews/DataCatalog/DataCatalogReference.jsx
  lib/ReactViews/Preview/MappablePreview.jsx
  test/Helpers/SimpleCatalogItem.ts
  test/Models/TerriaSpec.ts
  test/Models/WorkbenchSpec.ts
  test/ReactViews/Map/Panels/SharePanel/BuildShareLinkSpec.ts
Labels: High priority, T-Architecture/refactor, T-Bug, Version 8

#4986 Add multiplierDefaultDeltaStep Trait - which tries to calculate sensible multiplier for DistrectelyTimeVarying datasets
  CHANGES.md
  lib/ModelMixins/DiscretelyTimeVaryingMixin.ts
  lib/Traits/DiscretelyTimeVaryingTraits.ts
  lib/Traits/TimeVaryingTraits.ts
  test/ModelMixins/DiscretelyTimeVaryingMixinSpec.ts
Labels: C-Time, P-PacificMap, T-Enhancement

#5003 Wps fixes
  CHANGES.md
  lib/ModelMixins/CatalogFunctionJobMixin.ts
  lib/ModelMixins/CatalogFunctionMixin.ts
  lib/Models/CsvCatalogItem.ts
  lib/Models/FunctionParameters/FunctionParameter.ts
  lib/Models/UserDrawing.ts
  lib/Models/WebProcessingServiceCatalogFunctionJob.ts
  lib/ReactViews/Analytics/GenericParameterEditor.tsx
  lib/Traits/TableChartStyleTraits.ts
  package.json
Labels: High priority

#4975 Share keys
  .prettierignore
  .vscode/settings.json
  CHANGES.md
  lib/Models/MagdaReference.ts
  lib/Models/Terria.ts
  lib/Models/WebProcessingServiceCatalogFunctionJob.ts
  lib/Models/createCatalogItemFromFileOrUrl.ts
  lib/Models/createUrlReferenceFromUrl.ts
  lib/Models/updateModelFromJson.ts
  lib/Models/upsertModelFromJson.ts
  lib/ReactViews/ExplorerWindow/Tabs/MyDataTab/AddData.jsx
  lib/Traits/modelReferenceArrayTrait.ts
  test/Models/CatalogGroupSpec.ts
  test/Models/MagdaReferenceSpec.ts
  test/Models/TerriaSpec.ts
  test/Models/upsertModelFromJsonSpec.ts
  wwwroot/test/Magda/shareKeys/12f26f07-f39e-4753-979d-2de01af54bd1.json
  wwwroot/test/Magda/shareKeys/6b24aa39-1aa7-48d1-b6a6-9e755aff4476.json
  wwwroot/test/Magda/shareKeys/bfc69476-1c85-4208-9046-4f736bab9b8e.json
  wwwroot/test/Magda/shareKeys/map-config-example-new.json
  wwwroot/test/Magda/shareKeys/map-config-example-old.json
Labels: High priority
