Repository TerriaJS/terriajs, pull requests merged in 2020-06, with the labels that each got.

#4348 Mobx - catalog group fix
  CHANGES.md
  lib/Language/en/translation.json
  lib/Models/MagdaReference.ts
  lib/Models/StubCatalogItem.ts
  lib/Models/createStubCatalogItem.ts
  lib/Models/registerCatalogMembers.ts
  lib/Models/upsertModelFromJson.ts
  lib/Traits/modelReferenceArrayTrait.ts
  test/Models/CatalogGroupSpec.ts
  test/Models/MagdaReferenceSpec.ts
Labels: MobX

#4458 Add upload as tour point
  CHANGES.md
  lib/ReactViewModels/defaultTourPoints.ts
  lib/ReactViews/SidePanel/SidePanel.jsx
Labels: High priority

#4426 Mobx trainer
  CHANGES.md
  buildprocess/ci-values.yml
  lib/Language/en/translation.json
  lib/Models/Terria.ts
  lib/ReactViewModels/ViewState.ts
  lib/ReactViewModels/defaultHelpContent.ts
  lib/ReactViews/Generic/CloseButton.jsx
  lib/ReactViews/Icon.jsx
  lib/ReactViews/Map/MapNavigation.jsx
  lib/ReactViews/Map/MenuBar.jsx
  lib/ReactViews/Map/Panels/HelpPanel/HelpPanelItem.jsx
  lib/ReactViews/Map/Panels/HelpPanel/HelpVideoPanel.jsx
  lib/ReactViews/Map/Panels/HelpPanel/StyledHtml.jsx
  lib/ReactViews/Map/Panels/HelpPanel/TrainerPane.jsx
  lib/ReactViews/Map/TrainerBar/TrainerBar.tsx
  lib/ReactViews/SidePanel/FullScreenButton.jsx
  lib/ReactViews/SidePanel/full_screen_button.scss
  lib/ReactViews/SidePanel/full_screen_button.scss.d.ts
  lib/ReactViews/StandardUserInterface/StandardUserInterface.jsx
  lib/ReactViews/StandardUserInterface/standard-user-interface.scss
  lib/ReactViews/StandardUserInterface/standard-user-interface.scss.d.ts
  lib/Sass/common/_variables.scss
  lib/Sass/exports/_variables-export.scss
  lib/Sass/exports/_variables-export.scss.d.ts
  lib/Styled/Box.jsx
  lib/Styled/List.jsx
  lib/Styled/Select.tsx
  lib/Styled/mixins.js
  test/ReactViewModels/ViewStateSpec.ts
  test/ReactViews/Map/TrainerBar/TrainerBarSpec.tsx
  test/ReactViews/Map/TrainerBar/test-help-content.js
  wwwroot/images/icons/accordion-close.svg
  wwwroot/images/icons/accordion-open.svg
  wwwroot/images/icons/one-two-three.svg
Labels: High priority

#4459 Add "map state" map data count
  CHANGES.md
  lib/Language/en/translation.json
  lib/ReactViews/BottomDock/BottomDock.jsx
  lib/ReactViews/BottomDock/MapDataCount.jsx
  lib/ReactViews/HOCs/measureElement.js
  lib/ReactViews/Icon.jsx
  lib/Styled/ButtonAsLabel.jsx
  test/ReactViews/BottomDock/MapDataCountSpec.tsx
  wwwroot/images/icons/map-data-active.svg
  wwwroot/images/icons/map-data-inactive.svg
Labels: High priority, P - DigitalTwin

#4443 Changes for invoking MyData without using the ExplorerWindow component
  CHANGES.md
  lib/Language/en/translation.json
  lib/Models/addUserCatalogMember.ts
  lib/ReactViews/ExplorerWindow/ModalPopup.jsx
  lib/ReactViews/ExplorerWindow/Tabs.jsx
  lib/ReactViews/ExplorerWindow/Tabs/MyDataTab/AddData.jsx
  lib/ReactViews/ExplorerWindow/Tabs/MyDataTab/MyDataTab.jsx
  lib/ReactViews/Workbench/Controls/ViewingControls.jsx
Labels: High priority, P - DigitalTwin

#4398 Mobx tool tweaks
  CHANGES.md
  lib/ReactViewModels/ViewState.ts
  lib/ReactViews/Map/MapNavigation.jsx
  lib/ReactViews/MapIconButton/MapIconButton.jsx
  lib/ReactViews/Tool.tsx
  lib/ReactViews/Workbench/Controls/ViewingControls.jsx
  test/ReactViews/ToolButtonSpec.tsx
  test/ReactViews/ToolSpec.tsx
Labels: High priority, P - DigitalTwin

#4399 Model transformations, 3d tiles feature hiding
  CHANGES.md
  lib/ModelMixins/FeatureInfoMixin.ts
  lib/Models/Cesium.ts
  lib/Models/Cesium3DTilesCatalogItem.ts
  lib/Models/GltfCatalogItem.ts
  lib/ThirdParty/terriajs-cesium/index.d.ts
  lib/Traits/Cesium3DCatalogItemTraits.ts
  lib/Traits/GltfCatalogItemTraits.ts
  lib/Traits/GltfTraits.ts
  lib/Traits/HeadingPitchRollTraits.ts
  lib/Traits/PlaceEditorTraits.ts
  lib/Traits/TransformationTraits.ts
  test/Models/Cesium3DTilesCatalogItemSpec.ts
  wwwroot/test/Cesium3DTiles/tileset.json
Labels: High priority, P - DigitalTwin

#4467 Mobx refind help
  CHANGES.md
  lib/Language/en/translation.json
  lib/ReactViews/Generic/Prompt.jsx
  lib/ReactViews/Map/MapNavigation.jsx
  lib/ReactViews/Map/MenuBar.jsx
  lib/ReactViews/SidePanel/SidePanel.jsx
  lib/ReactViews/WelcomeMessage/WelcomeMessage.jsx
  test/ReactViews/Generic/PromptSpec.tsx
Labels: High priority, P-SatelliteImagery

#4463 Mobx tooltips
  CHANGES.md
  lib/Core/injectTerms.ts
  lib/Core/markdownToHtml.ts
  lib/Models/Terria.ts
  lib/ReactViewModels/defaultTerms.ts
  lib/ReactViews/Custom/TerriaTooltip.tsx
  lib/ReactViews/Custom/parseCustomMarkdownToReact.js
  lib/ReactViews/Custom/registerCustomComponentTypes.js
  lib/ReactViews/Generic/TooltipWrapper.tsx
  lib/ReactViews/Map/Panels/HelpPanel/HelpPanelItem.jsx
  lib/ReactViews/Map/Panels/HelpPanel/HelpVideoPanel.jsx
  lib/ReactViews/Map/Panels/HelpPanel/StyledHtml.jsx
  lib/ReactViews/Map/Panels/HelpPanel/TrainerPane.jsx
  lib/ReactViews/Map/TrainerBar/TrainerBar.tsx
  lib/ReactViews/Tour/TourPortal.jsx
  package.json
  test/Core/markdownToHtmlSpec.ts
  test/Map/StyledHtmlSpec.tsx
  test/Models/parseCustomMarkdownToReactTsSpec.ts
Labels: High priority, MobX

#4461 Mobx WebCoverageService "Clip and ship" for WMS
  CHANGES.md
  lib/Language/en/translation.json
  lib/Models/CsvCatalogItem.ts
  lib/Models/ExportableData.ts
  lib/Models/MapInteractionMode.ts
  lib/Models/UserDrawing.ts
  lib/Models/WebMapServiceCatalogItem.ts
  lib/Models/callWebCoverageService.js
  lib/Models/callWebCoverageService.ts
  lib/ReactViewModels/MouseCoords.ts
  lib/ReactViews/Analytics/LineParameterEditor.jsx
  lib/ReactViews/Analytics/ParameterEditor.jsx
  lib/ReactViews/Analytics/PolygonParameterEditor.jsx
  lib/ReactViews/Analytics/RectangleParameterEditor.jsx
  lib/ReactViews/Notification/MapInteractionWindow.jsx
  lib/ReactViews/Notification/MapInteractionWindow.tsx
  lib/ReactViews/Preview/Description.jsx
  lib/ReactViews/Preview/ExportData.tsx
  lib/ReactViews/Workbench/Controls/ViewingControls.jsx
  lib/Traits/WebMapServiceCatalogItemTraits.ts
Labels: MobX
