Repository TerriaJS/terriajs, pull requests merged in 2021-03, with the labels that each got.

#4877 Add time support for on ArcGisMapServerCatalogItem
  CHANGES.md
  lib/Core/createDiscreteTimes.ts
  lib/Models/ArcGisMapServerCatalogItem.ts
  lib/Models/WebMapServiceCatalogItem.ts
  lib/Traits/ArcGisMapServerCatalogItemTraits.ts
  test/Models/ArcGisMapServerCatalogItemSpec.ts
  wwwroot/test/ArcGisMapServer/time-enabled.json
Labels: Low priority

#5140 Configurable basemaps from init json
  CHANGES.md
  doc/connecting-to-data/catalog-functions.md
  doc/connecting-to-data/catalog-groups.md
  doc/connecting-to-data/catalog-items.md
  doc/customizing/initialization-files.md
  lib/Models/BaseMaps/BaseMapModel.ts
  lib/Models/BaseMaps/defaultBaseMaps.ts
  lib/Models/Terria.ts
  lib/ReactViews/Preview/DataPreviewMap.jsx
  lib/ViewModels/createAustraliaBaseMapOptions.js
  lib/ViewModels/createBingBaseMapOptions.ts
  lib/ViewModels/createGlobalBaseMapOptions.ts
  test/Models/TerriaSpec.ts
  wwwroot/images/australian-topo.png
  wwwroot/images/bing-aerial-labels.png
  wwwroot/images/bing-aerial.png
  wwwroot/images/bing-maps-roads.png
  wwwroot/images/black-marble.png
  wwwroot/images/dark-matter.png
  wwwroot/images/positron.png
Labels: PR blitz

#5366 Hide basemap entry in basemap menu
  CHANGES.md
  doc/customizing/initialization-files.md
  lib/Models/BaseMaps/BaseMapModel.ts
Labels: High priority
