Repository TerriaJS/terriajs, pull requests merged in 2021-04, with the labels that each got.

#5327 Add `WebMapService` support for WGS84 tiling scheme
  CHANGES.md
  lib/Models/WebMapServiceCapabilities.ts
  lib/Models/WebMapServiceCatalogItem.ts
  lib/Traits/WebMapServiceCatalogItemTraits.ts
  test/Models/WebMapServiceCatalogItemSpec.ts
  wwwroot/test/WMS/wms_crs.xml
Labels: High priority

#5367 add z-index to right group in mobile header so that buttons will appear over icons
  CHANGES.md
  lib/ReactViews/Mobile/mobile-header.scss
Labels: Medium priority

#5407 Handle errors while loading init sources
  CHANGES.md
  lib/Core/TerriaError.ts
  lib/Language/en/translation.json
  lib/Models/Terria.ts
  lib/Models/raiseErrorToUser.ts
  lib/ViewModels/TerriaViewer.ts
  lib/ViewModels/updateApplicationOnHashChange.js
  lib/ViewModels/updateApplicationOnHashChange.ts
  test/Models/TerriaSpec.ts
Labels: High priority

#5131 [#5008] More granular control over tools/panels
  lib/Models/IElementConfig.ts
  lib/Models/Terria.ts
  lib/ReactViews/BottomDock/MapDataCount.jsx
  lib/ReactViews/Feedback/FeedbackButton.jsx
  lib/ReactViews/HOCs/withControlledVisibility.tsx
  lib/ReactViews/Map/MapNavigation.jsx
  lib/ReactViews/Map/MenuBar.jsx
  lib/ReactViews/Map/Navigation/Compass.jsx
  lib/ReactViews/Map/Navigation/MeasureTool.jsx
  lib/ReactViews/Map/Navigation/MyLocation.jsx
  lib/ReactViews/Map/Navigation/ToggleSplitterTool.jsx
  lib/ReactViews/Map/Navigation/ZoomControl.jsx
  lib/ReactViews/SidePanel/FullScreenButton.jsx
  lib/ReactViews/StandardUserInterface/MapColumn.jsx
  lib/ReactViews/StandardUserInterface/StandardUserInterface.jsx
  lib/ReactViews/StandardUserInterface/customizable/MenuItem.jsx
  lib/ReactViews/StandardUserInterface/customizable/MenuPanel.jsx
Labels: High priority, P-PacificMap

#5315 Region map timeseries improvements
  CHANGES.md
  lib/ModelMixins/DiscretelyTimeVaryingMixin.ts
  lib/ModelMixins/TableMixin.ts
  lib/ReactViews/FeatureInfo/FeatureInfoSection.jsx
  lib/Table/TableStyle.ts
  lib/Traits/TableChartStyleTraits.ts
Labels: Medium priority

#5298 Fix czml catalog item so that it appears in the timeline
  CHANGES.md
  lib/Core/getDataType.js
  lib/ModelMixins/DiscretelyTimeVaryingMixin.ts
  lib/Models/CzmlCatalogItem.ts
  lib/Models/GlobeOrMap.ts
  lib/ReactViews/Clipboard.tsx
  lib/ReactViews/ExplorerWindow/Tabs/MyDataTab/AddData.jsx
  lib/ReactViews/Workbench/Controls/ViewingControls.jsx
  lib/Traits/CzmlCatalogItemTraits.ts
  test/Models/CesiumSpec.ts
  test/Models/CzmlCatalogItemSpec.js
  test/Models/CzmlCatalogItemSpec.ts
  test/Models/LeafletSpec.ts
  test/SpecMain.ts
Labels: Medium priority
