Repository TerriaJS/terriajs, pull requests merged in 2022-10, with the labels that each got.

#6571 Add support for `OpenDataSoftCatalogGroup` with more than 100 datasets
  CHANGES.md
  lib/Models/Catalog/CatalogGroups/OpenDataSoftCatalogGroup.ts
  test/Models/Catalog/CatalogGroups/OpenDataSoftCatalogGroupSpec.ts
  wwwroot/test/ods/datasets-over-100-1.json
  wwwroot/test/ods/datasets-over-100-2.json
Labels: platforms

#6548 Tweak `generateCatalogIndex` to use less memory
  CHANGES.md
  buildprocess/diffCatalogIndex.js
  buildprocess/generateCatalogIndex.ts
Labels: maintenance

#6534 Remove ObserveModelMixin and refresh some files
  CHANGES.md
  lib/Models/Terria.ts
  lib/ReactViewModels/ViewState.ts
  lib/ReactViews/HelpScreens/HelpMenuPanelBasic.jsx
  lib/ReactViews/HelpScreens/HelpOverlay.jsx
  lib/ReactViews/HelpScreens/HelpScreenWindow.jsx
  lib/ReactViews/HelpScreens/ObscureOverlay.jsx
  lib/ReactViews/Map/HelpButton/HelpButton.tsx
  lib/ReactViews/Map/MenuBar.jsx
  lib/ReactViews/Map/Panels/ToolsPanel/CountDatasets.jsx
  lib/ReactViews/Map/Panels/ToolsPanel/CountDatasets.tsx
  lib/ReactViews/Map/Panels/ToolsPanel/ToolsPanel.jsx
  lib/ReactViews/Map/Panels/ToolsPanel/tools-panel.scss
  lib/ReactViews/Map/Panels/ToolsPanel/tools-panel.scss.d.ts
  lib/ReactViews/Mobile/MobileMenu.jsx
  lib/ReactViews/ObserveModelMixin.js
  lib/ReactViews/RemovePanel/RemovePanel.jsx
  lib/ReactViews/RemovePanel/remove-panel.scss
  lib/ReactViews/RemovePanel/remove-panel.scss.d.ts
  lib/ReactViews/StandardUserInterface/MapColumn.jsx
  lib/ReactViews/Tour/TourOverlay.jsx
  package.json
  wwwroot/languages/en/translation.json
Labels: Waiting for PR Author, product

#6587 Change plugin name for runWebpack errors
  buildprocess/runWebpack.js
Labels: maintenance
